### ISSUE TITLE
Fault Tolerance when server crashes

### ISSUE THREAD

**Issue by mbajaj92** [harshini-shah/Location-Based-Messenger#35]
When the server crashes;
Read the DB to create the queues and the probe threads again. 
Changes statuses of Logged in Users to Logged in again (otherwise the probe will not start)

**Comment by harshini-shah** [comment]
@mbajaj92 - We aren't doing this right ? Close is if we are not, so we can track stuff better.

**Comment by mbajaj92** [comment]
Yes we are not doing this.

Regards,
Madhur J. Bajaj
