### ISSUE TITLE
Display Multiple Messages

### ISSUE THREAD

**Issue by mbajaj92** [harshini-shah/Location-Based-Messenger#36]
If there are multiple messages for a user, do not show pipes, separate them and then show properly

**Comment by harshini-shah** [comment]
Closed - https://github.com/harshini-shah/Location-Based-Messenger/commit/16cf9c1bc39718c8a55848c1affd69fa5da0c59f

**Comment by harshini-shah** [comment]
Done - https://github.com/harshini-shah/Location-Based-Messenger/commit/16cf9c1bc39718c8a55848c1affd69fa5da0c59f
