### ISSUE TITLE
Support Multicast

### ISSUE THREAD

**Issue by mbajaj92** [harshini-shah/Location-Based-Messenger#37]
1. The Names will be separated by pipes. 
2. Understand and add the messages to all the Queues
3. Keep a count in the Message - Message ID DB of number of receivers 
4. Decrement it every time we send a message to a receiver
5. When the count is 0, delete it.

**Comment by harshini-shah** [comment]
Adding @vignesh-sankar coz of the client side (displaying message to tell them how to do it). I am not sure if this will have to be totally revamped anyway for the app.

**Comment by harshini-shah** [comment]
Done 
https://github.com/harshini-shah/Location-Based-Messenger/pull/61
